### PR TITLE
Fmi user meeting presentations

### PR DESCRIPTION
**Pull request by chrbertsch**
Publish PDFs of Presentations from FMI User Meeting (presenters have agreed)

### CODE REVIEW

**Comment by sjoelund** [comment]
I would just put them as presentations directly at the top level. The FMI user meeting was not part of the conference proceedings after all.

**Comment by chrbertsch** [comment]
@sjoelund  and @lochel : could someone plesae review and merge this? Thanks!

**Comment by chrbertsch** [comment]
Will these presentations (together with the videos?) be linked from the program?
Or is the only way to access them via https://github.com/modelica/ModelicaConference2021/tree/master/presentations/FMI-User-Meeting ?

**Comment by sjoelund** [comment]
Someone would need to generate a webpage for them. They are available on the webpage, but not linked from anywhere:
https://2021.international.conference.modelica.org/presentations/FMI-User-Meeting/00_Modelica21_FMI_User_Meeting_Overview.pdf

presentations/FMI-User-Meeting/blabla.md could be created, giving some information + link to the PDF for example

**Pull request merged**
